//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public Nullable<int> Apartment { get; set; }
        public Nullable<int> DoorCode { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Note { get; set; }
        public int PaymentTypeId { get; set; }
        public string Status { get; set; }
    }
}
